apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-app
  template:
    metadata:
      labels:
        app: private-app
    spec:
      containers:
      - name: private-app
        image: <your-dockerhub-username>/<your-private-repo>:<tag>
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: private-app-service
spec:
  type: NodePort
  selector:
    app: private-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
